@file:Suppress("UnstableApiUsage")

pluginManagement {
    repositories {
        gradlePluginPortal()
        mavenCentral()
        mavenLocal()
    }
}

dependencyResolutionManagement {
    repositories {
        mavenCentral()
        google()
        mavenLocal()
    }
}

rootProject.name = "kilua-project"
include(":kilua")
include(":modules:kilua-animation")
include(":modules:kilua-annotations")
include(":modules:kilua-bootstrap")
include(":modules:kilua-bootstrap-icons")
include(":modules:kilua-common-types")
include(":modules:kilua-core-modules")
include(":modules:kilua-fontawesome")
include(":modules:kilua-i18n")
include(":modules:kilua-imask")
include(":modules:kilua-jetpack")
include(":modules:kilua-lazy-layouts")
include(":modules:kilua-leaflet")
include(":modules:kilua-marked")
include(":modules:kilua-rest")
include(":modules:kilua-routing")
include(":modules:kilua-rsup-progress")
include(":modules:kilua-sanitize-html")
include(":modules:kilua-select-remote")
include(":modules:kilua-splitjs")
include(":modules:kilua-ssr")
include(":modules:kilua-ssr-server")
include(":modules:kilua-ssr-server-javalin")
include(":modules:kilua-ssr-server-jooby")
include(":modules:kilua-ssr-server-ktor")
//include(":modules:kilua-ssr-server-micronaut")
include(":modules:kilua-ssr-server-spring-boot")
include(":modules:kilua-ssr-server-vertx")
include(":modules:kilua-svg")
include(":modules:kilua-tabulator")
include(":modules:kilua-tabulator-remote")
include(":modules:kilua-tailwindcss")
include(":modules:kilua-tempus-dominus")
include(":modules:kilua-testutils")
include(":modules:kilua-toastify")
include(":modules:kilua-tom-select")
include(":modules:kilua-tom-select-remote")
include(":modules:kilua-trix")
include(":plugins:kilua-gradle-plugin")
include(":plugins:kilua-ksp-processor")
include(":kilua-assets")
include(":examples:bootstrap-form")
include(":examples:hello-world")
include(":examples:js-framework-benchmark")
include(":examples:playground")
include(":examples:fullstack-ktor-koin")
include(":examples:ssr-javalin")
include(":examples:ssr-jooby")
include(":examples:ssr-ktor")
//include(":examples:ssr-micronaut")
//include(":examples:ssr-micronaut:application")
include(":examples:ssr-spring-boot")
include(":examples:ssr-spring-boot:application")
include(":examples:ssr-vertx")
include(":examples:todomvc")
include(":examples:todomvc-ballast")
include(":examples:realworld")
